# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
use_frameworks!

target 'PushIt' do
end

target 'PushItTests' do

end

target 'PushItUITests' do

end

target 'PushIt WatchKit App' do

end

target 'PushIt WatchKit Extension' do

end

